<a href="https://colab.research.google.com/github/saiakshitha28-collab/ML_LAB_2026-27/blob/main/pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Pandas Python Library**

**Introduction to Pandas**
Pandas is an open-source software library written for the Python programming language, primarily used for data manipulation and analysis. It provides powerful and flexible data structures designed to make working with tabular and time-series data both easy and intuitive.

**Key features and functionalities of Pandas include: Data Structures:**

Pandas introduces two primary data structures:

**Series:** A one-dimensional labeled array capable of holding any data type. It can be thought of as a single column in a spreadsheet.

**DataFrame:** A two-dimensional labeled data structure with columns of potentially different data types. It is similar to a spreadsheet or SQL table, providing a powerful way to represent and manipulate tabular data.

**What is pandas used for?**

pandas is used throughout the data analysis workflow. With pandas, you can:

1.Import datasets from databases, spreadsheets, comma-separated values (CSV) files, and more.

2.Clean datasets, for example, by dealing with missing values.

3.Tidy datasets by reshaping their structure into a suitable format for analysis.

4.Aggregate data by calculating summary statistics such as the mean of columns, correlation between them, and more.

5.Visualize datasets and uncover insights.

**Importing data in pandas**

In [1]:
import pandas as pd

**Importing CSV files**

Use **read_csv()** with the path to the CSV file to read a comma-separated values file

In [2]:
df=pd.read_csv("/content/sample_data/mnist_test.csv")

**df.head()** is used to display the top 5 records from data frame

In [3]:
df.head()

,7,0,0.1,0.2,0.3,0.4,0.5,0.6,0.7,0.8,...,0.658,0.659,0.660,0.661,0.662,0.663,0.664,0.665,0.666,0.667
0,2,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,4,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

**df.tail()** is used to display bottom 5 records from data frame.

In [4]:
df.tail()

,7,0,0.1,0.2,0.3,0.4,0.5,0.6,0.7,0.8,...,0.658,0.659,0.660,0.661,0.662,0.663,0.664,0.665,0.666,0.667
9994,2,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
9995,3,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
9996,4,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
9997,5,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
9998,6,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

**df.describe()** describes about whole dataframe columns and rows

In [5]:
df.describe()

,7,0,0.1,0.2,0.3,0.4,0.5,0.6,0.7,0.8,...,0.658,0.659,0.660,0.661,0.662,0.663,0.664,0.665,0.666,0.667
count,9999.000000,9999.0,9999.0,9999.0,9999.0,9999.0,9999.0,9999.0,9999.0,9999.0,...,9999.000000,9999.000000,9999.000000,9999.000000,9999.0,9999.0,9999.0,9999.0,9999.0,9999.0
mean,4.443144,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.179318,0.163616,0.052605,0.000600,0.0,0.0,0.0,0.0,0.0,0.0
std,2.895897,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,5.674433,5.736359,2.420125,0.060003,0.0,0.0,0.0,0.0,0.0,0.0
min,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.000000,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,0.0
25%,2.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.000000,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,0.0
50%,4.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.000000,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,0.0
75%,7.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.000000,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,0.0
max,9.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,253.000000,253.000000,156.000000,6.000000,0.0,0.0,0.0,0.0,0.0,0.0

**df.columns** is used to display all columns present in data frame.

In [7]:
df.columns

Index(['7', '0', '0.1', '0.2', '0.3', '0.4', '0.5', '0.6', '0.7', '0.8',
       ...
       '0.658', '0.659', '0.660', '0.661', '0.662', '0.663', '0.664', '0.665',
       '0.666', '0.667'],
      dtype='object', length=785)

**df.info()** gives information about the data frame about the no.of entries,columns,rows.

In [14]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9999 entries, 0 to 9998
Columns: 785 entries, 7 to 0.667
dtypes: int64(785)
memory usage: 59.9 MB

**importing excel file by read_excel()**

In [8]:
ff=pd.read_excel("/content/Student_Marks_Updated(1).xlsx")

In [9]:
ff.head()

           Name    Roll No.  Marks
0  Sai Akshitha  24AG1A66G4   8.65
1       Bhuvana  24AG1A66G3   6.25
2        Lvanya  24AG1A66F9   7.70
3       Shruthi  24AG1A66F3   8.00
4       Vasanth  24AG1A66G2   8.50

In [10]:
ff.tail()

        Name    Roll No.  Marks
4    Vasanth  24AG1A66G2   8.50
5   Tanishqa  24AG1A66H0   6.55
6  Tejaswini  24AG1A66G5   8.80
7    Nandini  24AG1A66G6   9.00
8    Abhinav  24AG1A66G7   7.80

In [11]:
ff.describe()

          Marks
count  9.000000
mean   7.916667
std    0.971146
min    6.250000
25%    7.700000
50%    8.000000
75%    8.650000
max    9.000000

In [12]:
ff.columns

Index(['Name', 'Roll No.', 'Marks'], dtype='object')

In [13]:
ff.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9 entries, 0 to 8
Data columns (total 3 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Name      9 non-null      object
 1   Roll No.  9 non-null      object
 2   Marks     9 non-null      float64
dtypes: float64(1), object(2)
memory usage: 348.0+ bytes

**importing json file using read_json()**

In [16]:
ff=pd.read_json("/content/sample_data/anscombe.json")

In [17]:
ff.head()

  Series   X     Y
0      I  10  8.04
1      I   8  6.95
2      I  13  7.58
3      I   9  8.81
4      I  11  8.33

In [18]:
ff.tail()

   Series   X      Y
39     IV   8   5.25
40     IV  19  12.50
41     IV   8   5.56
42     IV   8   7.91
43     IV   8   6.89

In [19]:
ff.describe()

               X          Y
count  44.000000  44.000000
mean    9.000000   7.500455
std     3.198837   1.959244
min     4.000000   3.100000
25%     7.000000   6.117500
50%     8.000000   7.520000
75%    11.000000   8.747500
max    19.000000  12.740000

In [20]:
ff.columns

Index(['Series', 'X', 'Y'], dtype='object')

In [21]:
ff.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 44 entries, 0 to 43
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Series  44 non-null     object
 1   X       44 non-null     int64
 2   Y       44 non-null     float64
dtypes: float64(1), int64(1), object(1)
memory usage: 1.2+ KB